# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 2000

[directory]
fish_style_pwd_dir_length = 1
read_only = " "

[git_branch]
symbol = " "

[aws]
symbol = " "

[c]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Android = " "
Arch = " "
Debian = " "
Linux = " "
Macos = " "
Manjaro = " "
NixOS = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "