shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
hooks.post = "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]
hooks.pre = """
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=bold,underline
export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
"""

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]
hooks.pre = "export ZSH_AUTOSUGGEST_STRATEGY=(history completion)"

#[plugins.zsh-completions]
#github = "zsh-users/zsh-completions"
#apply = ["defer"]

#[plugins.zsh-autocomplete]
#github = "marlonrichert/zsh-autocomplete"
#apply = ["defer"]

#[plugins.zeno]
#github = "yuki-yano/zeno.zsh"
#apply = ["defer"]
#hooks.pre = 'export ZENO_HOME="$HOME/dotfiles/zeno"'
#hooks.post = 'bindkey " " zeno-auto-snippet && bindkey "^m" zeno-auto-snippet-and-accept-line'

[plugins.zabrze]
inline = '''
export ZABRZE_CONFIG_HOME="$HOME/dotfiles/zabrze"
eval "$(zabrze init --bind-keys)"
'''

[plugins.ni]
github = "azu/ni.zsh"
apply = ["defer"]

[plugins.rtx]
inline = 'zsh-defer eval "$(rtx activate zsh)"'

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh)"'

